language: rust
os:
  - linux
env:
  global:
    - secure: FKHLHp6egVV/MM7sc+opZ1jPq5USZSLMvYGP+jGRNT+97BqyRBSNK/7ay3c2L1apy9Eu8QujNXNh18RndDVwQV91KxND82sgel+DwnyfhkauGZ6fDTt0t+40JPN4LdWrwiwhr9Jm1GneBINGNMWPihVPwVz5sd92VGJtFfJrWXQ=
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose
after_script:
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh